'use client';

import { useState, useEffect, useCallback } from 'react';
import { FaSave, FaEye, FaUndo } from 'react-icons/fa';
import { useToast } from '@/hooks/useToast';
import { 
  generateWatermarkSVG, 
  svgToDataUrl, 
  getAllWatermarkFonts,
  type WatermarkFontKey,
  type WatermarkOptions 
} from '@/lib/utils/autoGeneratedImages';

interface WatermarkSettings {
  text: string;
  opacity: number;
  position: 'diagonal' | 'corner' | 'center' | 'tile';
  fontSize: 'small' | 'medium' | 'large';
  color: string;
  enabled: boolean;
  fontKey: WatermarkFontKey;
  customFont: string;
  angle: number;
}

const DEFAULT_SETTINGS: WatermarkSettings = {
  text: 'GENFITY ORDER',
  opacity: 0.15,
  position: 'diagonal',
  fontSize: 'medium',
  color: '#000000',
  enabled: true,
  fontKey: 'arial',
  customFont: '',
  angle: -30,
};

const FONT_SIZE_MAP = {
  small: 0.04,
  medium: 0.06,
  large: 0.08,
};

// Get all available fonts
const AVAILABLE_FONTS = getAllWatermarkFonts();

/**
 * Watermark Settings Page
 * 
 * Admin page for customizing watermark appearance on stock photos
 */
export default function WatermarkSettingsPage() {
  const { showToast } = useToast();
  const [settings, setSettings] = useState<WatermarkSettings>(DEFAULT_SETTINGS);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [useCustomFont, setUseCustomFont] = useState(false);
  const [isPageLoading, setIsPageLoading] = useState(true);
  
  // Sample image for preview
  const sampleImageUrl = '/images/menu-badges/signature.png';
  
  // Load saved settings
  useEffect(() => {
    const loadSettings = async () => {
      setIsPageLoading(true);
      const saved = localStorage.getItem('watermark_settings');
      if (saved) {
        try {
          const parsed = JSON.parse(saved);
          setSettings({ ...DEFAULT_SETTINGS, ...parsed });
          setUseCustomFont(!!parsed.customFont);
        } catch {
          // Use defaults
        }
      }
      setIsPageLoading(false);
    };
    loadSettings();
  }, []);
  
  // Generate preview
  const generatePreview = useCallback(async () => {
    if (!settings.enabled) {
      setPreviewUrl(sampleImageUrl);
      return;
    }
    
    setIsLoading(true);
    try {
      // Generate watermark preview based on position
      const width = 400;
      const height = 400;
      
      const watermarkOptions: WatermarkOptions = {
        text: settings.text,
        opacity: settings.opacity,
        fontSize: FONT_SIZE_MAP[settings.fontSize],
        color: settings.color,
        fontKey: useCustomFont ? undefined : settings.fontKey,
        customFont: useCustomFont ? settings.customFont : undefined,
        angle: settings.angle,
        position: settings.position,
      };
      
      const watermarkSvg = generateWatermarkSVG(width, height, watermarkOptions);
      
      // For preview, show the watermark overlay on a gradient background
      const previewSvg = `
        <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
          <defs>
            <linearGradient id="bgGrad" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" style="stop-color:#f3f4f6"/>
              <stop offset="100%" style="stop-color:#e5e7eb"/>
            </linearGradient>
          </defs>
          <rect width="100%" height="100%" fill="url(#bgGrad)"/>
          <text x="50%" y="45%" text-anchor="middle" font-size="48" fill="#9ca3af" font-family="Arial">
            Sample Image
          </text>
          <text x="50%" y="55%" text-anchor="middle" font-size="24" fill="#9ca3af" font-family="Arial">
            Preview
          </text>
        </svg>
      `;
      
      // Combine with watermark
      const combinedSvg = `
        <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
          <image href="images/landing/mobile_mockup_iphone.png" width="100%" height="100%"/>
          <image href="${svgToDataUrl(watermarkSvg)}" width="100%" height="100%" opacity="${settings.opacity}"/>
        </svg>
      `;
      
      setPreviewUrl(svgToDataUrl(combinedSvg));
    } catch (error) {
      console.error('Failed to generate preview:', error);
    } finally {
      setIsLoading(false);
    }
  }, [settings]);
  
  // Update preview when settings change
  useEffect(() => {
    generatePreview();
  }, [generatePreview]);
  
  // Save settings
  const handleSave = async () => {
    setIsSaving(true);
    try {
      localStorage.setItem('watermark_settings', JSON.stringify(settings));
      
      // Also save to server if API exists
      const token = localStorage.getItem('accessToken');
      if (token) {
        try {
          await fetch('/api/admin/settings/watermark', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${token}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(settings),
          });
        } catch {
          // Server save failed, but local save succeeded
        }
      }
      
      showToast({
        variant: 'success',
        title: 'Settings Saved',
        message: 'Watermark settings have been saved successfully.',
      });
    } catch (error) {
      showToast({
        variant: 'error',
        title: 'Save Failed',
        message: 'Failed to save watermark settings.',
      });
    } finally {
      setIsSaving(false);
    }
  };
  
  // Reset to defaults
  const handleReset = () => {
    setSettings(DEFAULT_SETTINGS);
    showToast({
      variant: 'info',
      title: 'Settings Reset',
      message: 'Watermark settings have been reset to defaults.',
    });
  };
  
  if (isPageLoading) {
    return (
      <div className="min-h-[400px] flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Watermark Settings</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            Customize the watermark appearance for stock photos
          </p>
        </div>
      </div>

      {/* Stats */}
      <div className="grid gap-4 sm:grid-cols-4">
        <div className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-200 dark:border-gray-700">
          <p className="text-sm text-gray-500 dark:text-gray-400">Status</p>
          <p className={`text-2xl font-bold mt-1 ${settings.enabled ? 'text-green-600 dark:text-green-400' : 'text-gray-400'}`}>
            {settings.enabled ? 'Enabled' : 'Disabled'}
          </p>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-200 dark:border-gray-700">
          <p className="text-sm text-gray-500 dark:text-gray-400">Position</p>
          <p className="text-2xl font-bold text-gray-900 dark:text-white mt-1 capitalize">{settings.position}</p>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-200 dark:border-gray-700">
          <p className="text-sm text-gray-500 dark:text-gray-400">Opacity</p>
          <p className="text-2xl font-bold text-gray-900 dark:text-white mt-1">{Math.round(settings.opacity * 100)}%</p>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-200 dark:border-gray-700">
          <p className="text-sm text-gray-500 dark:text-gray-400">Font Size</p>
          <p className="text-2xl font-bold text-gray-900 dark:text-white mt-1 capitalize">{settings.fontSize}</p>
        </div>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Settings Form */}
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-6">
            Configuration
          </h2>
          
          {/* Enable/Disable */}
          <div className="mb-6">
            <label className="flex items-center gap-3 cursor-pointer">
              <input
                type="checkbox"
                checked={settings.enabled}
                onChange={(e) => setSettings({ ...settings, enabled: e.target.checked })}
                className="w-5 h-5 rounded border-gray-300 text-blue-500 focus:ring-blue-500"
              />
              <span className="text-sm font-medium text-gray-900 dark:text-white">
                Enable Watermark
              </span>
            </label>
          </div>
          
          {/* Watermark Text */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Watermark Text
            </label>
            <input
              type="text"
              value={settings.text}
              onChange={(e) => setSettings({ ...settings, text: e.target.value })}
              disabled={!settings.enabled}
              placeholder="Enter watermark text"
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white disabled:opacity-50"
            />
          </div>
          
          {/* Position */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Position
            </label>
            <div className="grid grid-cols-2 gap-2">
              {(['diagonal', 'corner', 'center', 'tile'] as const).map((pos) => (
                <button
                  key={pos}
                  onClick={() => setSettings({ ...settings, position: pos })}
                  disabled={!settings.enabled}
                  className={`px-4 py-2 text-sm font-medium rounded-lg border transition-colors ${
                    settings.position === pos
                      ? 'border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-900/20 dark:text-blue-400'
                      : 'border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'
                  } disabled:opacity-50`}
                >
                  {pos.charAt(0).toUpperCase() + pos.slice(1)}
                </button>
              ))}
            </div>
          </div>
          
          {/* Opacity */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Opacity: {Math.round(settings.opacity * 100)}%
            </label>
            <input
              type="range"
              min="5"
              max="50"
              value={settings.opacity * 100}
              onChange={(e) => setSettings({ ...settings, opacity: parseInt(e.target.value) / 100 })}
              disabled={!settings.enabled}
              className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 disabled:opacity-50"
            />
            <div className="flex justify-between text-xs text-gray-500 mt-1">
              <span>5%</span>
              <span>50%</span>
            </div>
          </div>
          
          {/* Font Size */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Font Size
            </label>
            <div className="flex gap-2">
              {(['small', 'medium', 'large'] as const).map((size) => (
                <button
                  key={size}
                  onClick={() => setSettings({ ...settings, fontSize: size })}
                  disabled={!settings.enabled}
                  className={`flex-1 px-4 py-2 text-sm font-medium rounded-lg border transition-colors ${
                    settings.fontSize === size
                      ? 'border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-900/20 dark:text-blue-400'
                      : 'border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'
                  } disabled:opacity-50`}
                >
                  {size.charAt(0).toUpperCase() + size.slice(1)}
                </button>
              ))}
            </div>
          </div>
          
          {/* Font Selection */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Font
            </label>
            
            {/* Toggle between preset and custom font */}
            <div className="flex items-center gap-4 mb-3">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="radio"
                  checked={!useCustomFont}
                  onChange={() => setUseCustomFont(false)}
                  disabled={!settings.enabled}
                  className="text-blue-500 focus:ring-blue-500"
                />
                <span className="text-sm text-gray-700 dark:text-gray-300">Preset Font</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="radio"
                  checked={useCustomFont}
                  onChange={() => setUseCustomFont(true)}
                  disabled={!settings.enabled}
                  className="text-blue-500 focus:ring-blue-500"
                />
                <span className="text-sm text-gray-700 dark:text-gray-300">Custom Font</span>
              </label>
            </div>
            
            {!useCustomFont ? (
              <select
                value={settings.fontKey}
                onChange={(e) => setSettings({ ...settings, fontKey: e.target.value as WatermarkFontKey })}
                disabled={!settings.enabled}
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white disabled:opacity-50"
              >
                {Object.entries(AVAILABLE_FONTS).map(([key, font]) => (
                  <option key={key} value={key} style={{ fontFamily: font.family }}>
                    {font.name}
                  </option>
                ))}
              </select>
            ) : (
              <input
                type="text"
                value={settings.customFont}
                onChange={(e) => setSettings({ ...settings, customFont: e.target.value })}
                disabled={!settings.enabled}
                placeholder="e.g., 'Roboto', sans-serif"
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white disabled:opacity-50"
              />
            )}
            
            {/* Font Preview */}
            <div 
              className="mt-2 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg text-center"
              style={{ 
                fontFamily: useCustomFont 
                  ? (settings.customFont || 'Arial, sans-serif') 
                  : AVAILABLE_FONTS[settings.fontKey]?.family 
              }}
            >
              <span className="text-lg font-bold text-gray-900 dark:text-white">
                {settings.text || 'Sample Text'}
              </span>
            </div>
          </div>
          
          {/* Rotation Angle (only for diagonal and center) */}
          {(settings.position === 'diagonal' || settings.position === 'center') && (
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Rotation Angle: {settings.angle}°
              </label>
              <input
                type="range"
                min="-90"
                max="90"
                value={settings.angle}
                onChange={(e) => setSettings({ ...settings, angle: parseInt(e.target.value) })}
                disabled={!settings.enabled}
                className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 disabled:opacity-50"
              />
              <div className="flex justify-between text-xs text-gray-500 mt-1">
                <span>-90°</span>
                <span>0°</span>
                <span>90°</span>
              </div>
            </div>
          )}
          
          {/* Color */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Color
            </label>
            <div className="flex items-center gap-3">
              <input
                type="color"
                value={settings.color}
                onChange={(e) => setSettings({ ...settings, color: e.target.value })}
                disabled={!settings.enabled}
                className="w-12 h-10 rounded border border-gray-300 dark:border-gray-600 cursor-pointer disabled:opacity-50"
              />
              <input
                type="text"
                value={settings.color}
                onChange={(e) => setSettings({ ...settings, color: e.target.value })}
                disabled={!settings.enabled}
                className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white disabled:opacity-50"
              />
            </div>
          </div>
          
          {/* Action Buttons */}
          <div className="flex gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">
            <button
              onClick={handleReset}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
            >
              <FaUndo className="w-4 h-4" />
              Reset
            </button>
            <button
              onClick={handleSave}
              disabled={isSaving}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-white bg-blue-500 rounded-lg hover:bg-blue-600 transition-colors disabled:opacity-50"
            >
              <FaSave className="w-4 h-4" />
              {isSaving ? 'Saving...' : 'Save Settings'}
            </button>
          </div>
        </div>
        
        {/* Preview */}
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
              Preview
            </h2>
            <button
              onClick={generatePreview}
              disabled={isLoading}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-blue-600 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-colors"
            >
              <FaEye className="w-4 h-4" />
              Refresh
            </button>
          </div>
          
          <div className="aspect-square rounded-lg overflow-hidden bg-gray-100 dark:bg-gray-700 border border-gray-200 dark:border-gray-600">
            {isLoading ? (
              <div className="w-full h-full flex items-center justify-center">
                <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin" />
              </div>
            ) : previewUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={previewUrl}
                alt="Watermark Preview"
                className="w-full h-full object-contain"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-gray-500">
                No preview available
              </div>
            )}
          </div>
          
          <p className="mt-4 text-sm text-gray-500 dark:text-gray-400 text-center">
            This preview shows how the watermark will appear on images.
          </p>
        </div>
      </div>
      
      {/* Usage Info */}
      <div className="bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-200 dark:border-blue-800 p-6">
        <h3 className="text-sm font-semibold text-blue-900 dark:text-blue-100 mb-2">
          How Watermarks Work
        </h3>
        <ul className="text-sm text-blue-700 dark:text-blue-300 space-y-1 list-disc list-inside">
          <li>Watermarks are automatically applied to stock photos when used</li>
          <li><strong>Diagonal:</strong> Text repeats across the entire image at an angle</li>
          <li><strong>Corner:</strong> Small, subtle text in the bottom-right corner</li>
          <li><strong>Center:</strong> Single watermark in the center of the image</li>
          <li><strong>Tile:</strong> Grid pattern of watermarks across the image</li>
        </ul>
        
        <h3 className="text-sm font-semibold text-blue-900 dark:text-blue-100 mt-4 mb-2">
          Font Options
        </h3>
        <ul className="text-sm text-blue-700 dark:text-blue-300 space-y-1 list-disc list-inside">
          <li><strong>Preset Fonts:</strong> Choose from 11 commonly available system fonts</li>
          <li><strong>Custom Font:</strong> Enter any font family available on your system</li>
          <li>Use quotes for fonts with spaces: &apos;Times New Roman&apos;, serif</li>
        </ul>
        
        <h3 className="text-sm font-semibold text-blue-900 dark:text-blue-100 mt-4 mb-2">
          Performance
        </h3>
        <ul className="text-sm text-blue-700 dark:text-blue-300 space-y-1 list-disc list-inside">
          <li>Watermarks are cached for improved performance</li>
          <li>Cache automatically refreshes when settings change</li>
          <li>No additional server load after initial generation</li>
        </ul>
      </div>
    </div>
  );
}
