'use client';

import { useState, useEffect, useCallback } from 'react';
import { FaSave, FaEye, FaUndo } from 'react-icons/fa';
import { useToast } from '@/hooks/useToast';
import { applyWatermarkToImage, generateWatermarkSVG, generateCornerWatermarkSVG, svgToDataUrl } from '@/lib/utils/autoGeneratedImages';

interface WatermarkSettings {
  text: string;
  opacity: number;
  position: 'diagonal' | 'corner' | 'center' | 'tile';
  fontSize: 'small' | 'medium' | 'large';
  color: string;
  enabled: boolean;
}

const DEFAULT_SETTINGS: WatermarkSettings = {
  text: 'GENFITY ORDER',
  opacity: 0.15,
  position: 'diagonal',
  fontSize: 'medium',
  color: '#000000',
  enabled: true,
};

const FONT_SIZE_MAP = {
  small: 0.04,
  medium: 0.06,
  large: 0.08,
};

/**
 * Watermark Settings Page
 * 
 * Admin page for customizing watermark appearance on stock photos
 */
export default function WatermarkSettingsPage() {
  const { showToast } = useToast();
  const [settings, setSettings] = useState<WatermarkSettings>(DEFAULT_SETTINGS);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  
  // Sample image for preview
  const sampleImageUrl = '/images/menu-badges/signature.png';
  
  // Load saved settings
  useEffect(() => {
    const saved = localStorage.getItem('watermark_settings');
    if (saved) {
      try {
        setSettings(JSON.parse(saved));
      } catch {
        // Use defaults
      }
    }
  }, []);
  
  // Generate preview
  const generatePreview = useCallback(async () => {
    if (!settings.enabled) {
      setPreviewUrl(sampleImageUrl);
      return;
    }
    
    setIsLoading(true);
    try {
      // Generate watermark preview based on position
      const width = 400;
      const height = 400;
      
      let watermarkSvg: string;
      
      if (settings.position === 'corner') {
        watermarkSvg = generateCornerWatermarkSVG(width, height, settings.text);
      } else {
        watermarkSvg = generateWatermarkSVG(width, height, settings.text);
      }
      
      // For preview, show the watermark overlay on a gradient background
      const previewSvg = `
        <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
          <defs>
            <linearGradient id="bgGrad" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" style="stop-color:#f3f4f6"/>
              <stop offset="100%" style="stop-color:#e5e7eb"/>
            </linearGradient>
          </defs>
          <rect width="100%" height="100%" fill="url(#bgGrad)"/>
          <text x="50%" y="45%" text-anchor="middle" font-size="48" fill="#9ca3af" font-family="Arial">
            Sample Image
          </text>
          <text x="50%" y="55%" text-anchor="middle" font-size="24" fill="#9ca3af" font-family="Arial">
            Preview
          </text>
        </svg>
      `;
      
      // Combine with watermark
      const combinedSvg = `
        <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">
          <image href="${svgToDataUrl(previewSvg)}" width="100%" height="100%"/>
          <image href="${svgToDataUrl(watermarkSvg)}" width="100%" height="100%" opacity="${settings.opacity}"/>
        </svg>
      `;
      
      setPreviewUrl(svgToDataUrl(combinedSvg));
    } catch (error) {
      console.error('Failed to generate preview:', error);
    } finally {
      setIsLoading(false);
    }
  }, [settings]);
  
  // Update preview when settings change
  useEffect(() => {
    generatePreview();
  }, [generatePreview]);
  
  // Save settings
  const handleSave = async () => {
    setIsSaving(true);
    try {
      localStorage.setItem('watermark_settings', JSON.stringify(settings));
      
      // Also save to server if API exists
      const token = localStorage.getItem('accessToken');
      if (token) {
        try {
          await fetch('/api/admin/settings/watermark', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${token}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(settings),
          });
        } catch {
          // Server save failed, but local save succeeded
        }
      }
      
      showToast({
        variant: 'success',
        title: 'Settings Saved',
        message: 'Watermark settings have been saved successfully.',
      });
    } catch (error) {
      showToast({
        variant: 'error',
        title: 'Save Failed',
        message: 'Failed to save watermark settings.',
      });
    } finally {
      setIsSaving(false);
    }
  };
  
  // Reset to defaults
  const handleReset = () => {
    setSettings(DEFAULT_SETTINGS);
    showToast({
      variant: 'info',
      title: 'Settings Reset',
      message: 'Watermark settings have been reset to defaults.',
    });
  };
  
  return (
    <div className="p-6 max-w-4xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
          Watermark Settings
        </h1>
        <p className="mt-2 text-gray-600 dark:text-gray-400">
          Customize the watermark appearance for stock photos
        </p>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Settings Form */}
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-6">
            Configuration
          </h2>
          
          {/* Enable/Disable */}
          <div className="mb-6">
            <label className="flex items-center gap-3 cursor-pointer">
              <input
                type="checkbox"
                checked={settings.enabled}
                onChange={(e) => setSettings({ ...settings, enabled: e.target.checked })}
                className="w-5 h-5 rounded border-gray-300 text-brand-500 focus:ring-brand-500"
              />
              <span className="text-sm font-medium text-gray-900 dark:text-white">
                Enable Watermark
              </span>
            </label>
          </div>
          
          {/* Watermark Text */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Watermark Text
            </label>
            <input
              type="text"
              value={settings.text}
              onChange={(e) => setSettings({ ...settings, text: e.target.value })}
              disabled={!settings.enabled}
              placeholder="Enter watermark text"
              className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-brand-500 focus:border-transparent dark:bg-gray-700 dark:text-white disabled:opacity-50"
            />
          </div>
          
          {/* Position */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Position
            </label>
            <div className="grid grid-cols-2 gap-2">
              {(['diagonal', 'corner', 'center', 'tile'] as const).map((pos) => (
                <button
                  key={pos}
                  onClick={() => setSettings({ ...settings, position: pos })}
                  disabled={!settings.enabled}
                  className={`px-4 py-2 text-sm font-medium rounded-lg border transition-colors ${
                    settings.position === pos
                      ? 'border-brand-500 bg-brand-50 text-brand-700 dark:bg-brand-900/20 dark:text-brand-400'
                      : 'border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'
                  } disabled:opacity-50`}
                >
                  {pos.charAt(0).toUpperCase() + pos.slice(1)}
                </button>
              ))}
            </div>
          </div>
          
          {/* Opacity */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Opacity: {Math.round(settings.opacity * 100)}%
            </label>
            <input
              type="range"
              min="5"
              max="50"
              value={settings.opacity * 100}
              onChange={(e) => setSettings({ ...settings, opacity: parseInt(e.target.value) / 100 })}
              disabled={!settings.enabled}
              className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 disabled:opacity-50"
            />
            <div className="flex justify-between text-xs text-gray-500 mt-1">
              <span>5%</span>
              <span>50%</span>
            </div>
          </div>
          
          {/* Font Size */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Font Size
            </label>
            <div className="flex gap-2">
              {(['small', 'medium', 'large'] as const).map((size) => (
                <button
                  key={size}
                  onClick={() => setSettings({ ...settings, fontSize: size })}
                  disabled={!settings.enabled}
                  className={`flex-1 px-4 py-2 text-sm font-medium rounded-lg border transition-colors ${
                    settings.fontSize === size
                      ? 'border-brand-500 bg-brand-50 text-brand-700 dark:bg-brand-900/20 dark:text-brand-400'
                      : 'border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'
                  } disabled:opacity-50`}
                >
                  {size.charAt(0).toUpperCase() + size.slice(1)}
                </button>
              ))}
            </div>
          </div>
          
          {/* Color */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Color
            </label>
            <div className="flex items-center gap-3">
              <input
                type="color"
                value={settings.color}
                onChange={(e) => setSettings({ ...settings, color: e.target.value })}
                disabled={!settings.enabled}
                className="w-12 h-10 rounded border border-gray-300 dark:border-gray-600 cursor-pointer disabled:opacity-50"
              />
              <input
                type="text"
                value={settings.color}
                onChange={(e) => setSettings({ ...settings, color: e.target.value })}
                disabled={!settings.enabled}
                className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-brand-500 focus:border-transparent dark:bg-gray-700 dark:text-white disabled:opacity-50"
              />
            </div>
          </div>
          
          {/* Action Buttons */}
          <div className="flex gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">
            <button
              onClick={handleReset}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
            >
              <FaUndo className="w-4 h-4" />
              Reset
            </button>
            <button
              onClick={handleSave}
              disabled={isSaving}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium text-white bg-brand-500 rounded-lg hover:bg-brand-600 transition-colors disabled:opacity-50"
            >
              <FaSave className="w-4 h-4" />
              {isSaving ? 'Saving...' : 'Save Settings'}
            </button>
          </div>
        </div>
        
        {/* Preview */}
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
              Preview
            </h2>
            <button
              onClick={generatePreview}
              disabled={isLoading}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-brand-600 dark:text-brand-400 hover:bg-brand-50 dark:hover:bg-brand-900/20 rounded-lg transition-colors"
            >
              <FaEye className="w-4 h-4" />
              Refresh
            </button>
          </div>
          
          <div className="aspect-square rounded-lg overflow-hidden bg-gray-100 dark:bg-gray-700 border border-gray-200 dark:border-gray-600">
            {isLoading ? (
              <div className="w-full h-full flex items-center justify-center">
                <div className="w-8 h-8 border-4 border-brand-500 border-t-transparent rounded-full animate-spin" />
              </div>
            ) : previewUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={previewUrl}
                alt="Watermark Preview"
                className="w-full h-full object-contain"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-gray-500">
                No preview available
              </div>
            )}
          </div>
          
          <p className="mt-4 text-sm text-gray-500 dark:text-gray-400 text-center">
            This preview shows how the watermark will appear on images.
          </p>
        </div>
      </div>
      
      {/* Usage Info */}
      <div className="mt-8 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-200 dark:border-blue-800 p-6">
        <h3 className="text-sm font-semibold text-blue-900 dark:text-blue-100 mb-2">
          How Watermarks Work
        </h3>
        <ul className="text-sm text-blue-700 dark:text-blue-300 space-y-1 list-disc list-inside">
          <li>Watermarks are automatically applied to stock photos when used</li>
          <li><strong>Diagonal:</strong> Text repeats across the entire image at an angle</li>
          <li><strong>Corner:</strong> Small, subtle text in the bottom-right corner</li>
          <li><strong>Center:</strong> Single watermark in the center of the image</li>
          <li><strong>Tile:</strong> Grid pattern of watermarks across the image</li>
        </ul>
      </div>
    </div>
  );
}
