'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { generateLogoDataUrl } from '@/lib/utils/autoGeneratedImages';

interface OpeningHour {
    id: string | bigint;
    dayOfWeek: number;
    isClosed: boolean;
    is24Hours: boolean;
    openTime?: string;
    closeTime?: string;
}

interface MerchantInfo {
    name: string;
    address?: string;
    phone?: string;
    logoUrl?: string;
    openingHours: OpeningHour[];
    currency?: string;
    country?: string;
    latitude?: number | null;
    longitude?: number | null;
}

interface OutletInfoModalProps {
    isOpen: boolean;
    onClose: () => void;
    merchant: MerchantInfo;
    merchantCode?: string;
}

const dayNames = ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'];

export default function OutletInfoModal({ isOpen, onClose, merchant, merchantCode }: OutletInfoModalProps) {
    const [showShareModal, setShowShareModal] = useState(false);
    const [copySuccess, setCopySuccess] = useState(false);
    const [isClosing, setIsClosing] = useState(false);

    // Generate share URL - avoid double slash when merchantCode is empty
    const shareUrl = typeof window !== 'undefined'
        ? merchantCode
            ? `${window.location.origin}/${merchantCode}/order?mode=dinein`
            : window.location.origin
        : '';

    // Handle smooth close
    const handleClose = () => {
        setIsClosing(true);
        setTimeout(() => {
            setIsClosing(false);
            onClose();
        }, 250); // Match animation duration
    };

    // Prevent body scroll when modal is open
    useEffect(() => {
        if (isOpen) {
            document.body.style.overflow = 'hidden';
        } else {
            document.body.style.overflow = 'unset';
        }
        return () => {
            document.body.style.overflow = 'unset';
        };
    }, [isOpen]);

    if (!isOpen) return null;

    // Get current day of week
    const currentDay = new Date().getDay();

    // Share handlers
    const handleCopyLink = async () => {
        try {
            await navigator.clipboard.writeText(shareUrl);
            setCopySuccess(true);
            setTimeout(() => setCopySuccess(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    const handleShareX = () => {
        const text = `Check out ${merchant.name}!`;
        window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(shareUrl)}`, '_blank');
    };

    const handleShareFacebook = () => {
        window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`, '_blank');
    };

    const handleShareWhatsApp = () => {
        const text = `Check out ${merchant.name}! ${shareUrl}`;
        window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
    };

    const handleShareLine = () => {
        const text = `Check out ${merchant.name}!`;
        window.open(`https://social-plugins.line.me/lineit/share?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(text)}`, '_blank');
    };

    const handleShareEmail = () => {
        const subject = `Check out ${merchant.name}!`;
        const body = `I found this great place: ${merchant.name}\n\n${shareUrl}`;
        window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`, '_blank');
    };

    return (
        <>
            {/* Backdrop */}
            <div
                className={`fixed inset-0 bg-black/50 z-1000 transition-opacity duration-250 ${isClosing ? 'opacity-0' : 'opacity-100'}`}
                onClick={handleClose}
            />

            {/* Modal */}
            <div className="fixed inset-0 z-1000 flex items-end justify-center pointer-events-none">
                <div className={`w-full max-w-[500px] bg-white rounded-t-2xl shadow-2xl pointer-events-auto ${isClosing ? 'animate-slide-down' : 'animate-slide-up'}`}>

                    {/* Header */}
                    <header className="relative shadow-[0_4px_12px_rgba(0,0,0,0.08)]">
                        <div className="flex items-center px-4 py-3">
                            <div className="flex-1 text-center font-semibold text-gray-900">
                                Outlet Info
                            </div>
                        </div>
                    </header>
                    {/* Content */}
                    <div className="max-h-[80vh] overflow-y-auto">
                        {/* Merchant Name & Address */}
                        <div className="relative px-4 py-6">
                            <h2 className="text-xl font-bold text-gray-900 mb-3">
                                {merchant.name}
                            </h2>

                            {merchant.address && (
                                <div className="flex gap-2 mt-2">
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" className="text-gray-900 shrink-0 mt-0.5">
                                        <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z" />
                                    </svg>
                                    <div className="flex-1 text-xs font-light text-gray-900 leading-relaxed">
                                        {merchant.address}
                                    </div>
                                    {/* Share Button */}
                                    <button
                                        onClick={() => setShowShareModal(true)}
                                        className="w-9 h-9 flex items-center justify-center rounded-full bg-gray-100 hover:bg-gray-200 transition-colors shrink-0"
                                        aria-label="Share"
                                    >
                                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                            <circle cx="18" cy="5" r="3" />
                                            <circle cx="6" cy="12" r="3" />
                                            <circle cx="18" cy="19" r="3" />
                                            <path d="M8.59 13.51l6.83 3.98M15.41 6.51l-6.82 3.98" />
                                        </svg>
                                    </button>
                                </div>
                            )}

                            {/* Country & Currency Info */}
                            {(merchant.country || merchant.currency) && (
                                <div className="flex items-center gap-3 mt-3 text-xs text-gray-600">
                                    {merchant.country && (
                                        <span className="flex items-center gap-1">
                                            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" className="text-gray-500">
                                                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z" />
                                            </svg>
                                            {merchant.country}
                                        </span>
                                    )}
                                    {merchant.currency && (
                                        <span className="flex items-center gap-1">
                                            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" className="text-gray-500">
                                                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1.41 16.09V20h-2.67v-1.93c-1.71-.36-3.16-1.46-3.27-3.4h1.96c.1 1.05.82 1.87 2.65 1.87 1.96 0 2.4-.98 2.4-1.59 0-.83-.44-1.61-2.67-2.14-2.48-.6-4.18-1.62-4.18-3.67 0-1.72 1.39-2.84 3.11-3.21V4h2.67v1.95c1.86.45 2.79 1.86 2.85 3.39H14.3c-.05-1.11-.64-1.87-2.22-1.87-1.5 0-2.4.68-2.4 1.64 0 .84.65 1.39 2.67 1.91s4.18 1.39 4.18 3.91c-.01 1.83-1.38 2.83-3.12 3.16z" />
                                            </svg>
                                            {merchant.currency}
                                        </span>
                                    )}
                                </div>
                            )}

                        </div>

                        {/* Contact Actions */}
                        <div className="flex items-center gap-2 px-4 pb-2 border-b border-gray-200">
                            {merchant.phone && (
                                <a
                                    href={`tel:${merchant.phone}`}
                                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 text-xs font-medium text-gray-700 bg-white border border-gray-400 rounded-md hover:bg-gray-50 transition-colors shadow-md"
                                >
                                    <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                                        <path d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z" />
                                    </svg>
                                    Contact Us
                                </a>
                            )}

                            {(merchant.address || (merchant.latitude && merchant.longitude)) && (
                                <a
                                    href={merchant.latitude && merchant.longitude
                                        ? `https://www.google.com/maps/search/?api=1&query=${merchant.latitude},${merchant.longitude}`
                                        : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(merchant.address || '')}`
                                    }
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex-1 flex items-center justify-center gap-2 px-3 py-2 text-xs font-medium text-gray-700 bg-white border border-gray-400 rounded-md hover:bg-gray-50 transition-colors shadow-md"
                                >
                                    <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                                        <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z" />
                                    </svg>
                                    Visit Us
                                </a>
                            )}
                        </div>

                        {/* Operating Hours */}
                        <div className="px-4 py-6">
                            <h3 className="text-base font-semibold text-gray-900 mb-4">
                                Operational Hours
                            </h3>

                            <div>
                                {merchant.openingHours
                                    .sort((a, b) => {
                                        // Sort: Monday first, then rest of week, Sunday last
                                        const aDay = a.dayOfWeek === 0 ? 7 : a.dayOfWeek;
                                        const bDay = b.dayOfWeek === 0 ? 7 : b.dayOfWeek;
                                        return aDay - bDay;
                                    })
                                    .map((hours, index) => {
                                        const isToday = hours.dayOfWeek === currentDay;
                                        const isLast = index === merchant.openingHours.length - 1;
                                        return (
                                            <div key={hours.id.toString()}>
                                                <div className="flex items-center justify-between py-3">
                                                    <span className={`text-xs uppercase pl-3 ${isToday
                                                        ? 'text-gray-900 font-bold'
                                                        : 'text-gray-600 font-light'
                                                        }`}>
                                                        {dayNames[hours.dayOfWeek]}
                                                    </span>

                                                    <span className={`text-xs ${isToday
                                                        ? 'text-gray-900 font-medium'
                                                        : 'text-gray-600 font-normal'
                                                        }`}>
                                                        {hours.isClosed
                                                            ? 'Closed'
                                                            : hours.is24Hours
                                                                ? 'Open 24 hours'
                                                                : `${hours.openTime} - ${hours.closeTime}`}
                                                    </span>
                                                </div>
                                                {!isLast && (
                                                    <div className="ml-3 mr-0">
                                                        <div className="border-b border-gray-200"></div>
                                                    </div>
                                                )}
                                            </div>
                                        );
                                    })}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Share Modal - "Bagikan ke Temanmu" */}
            {showShareModal && (
                <>
                    {/* Share Modal Backdrop */}
                    <div
                        className="fixed inset-0 bg-black/60 z-1010 transition-opacity"
                        onClick={() => setShowShareModal(false)}
                    />

                    {/* Share Modal Content */}
                    <div className="fixed inset-0 z-1010 flex items-center justify-center p-4">
                        <div className="w-full max-w-[400px] bg-white rounded-2xl shadow-2xl animate-scale-in">
                            {/* Header */}
                            <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200">
                                <h3 className="text-lg font-semibold text-gray-900">
                                    Share to Your Friend
                                </h3>
                                <button
                                    onClick={() => setShowShareModal(false)}
                                    className="w-8 h-8 flex items-center justify-center rounded-full hover:bg-gray-100 transition-colors"
                                    aria-label="Close"
                                >
                                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                                        <path d="M15 5L5 15M5 5L15 15" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
                                    </svg>
                                </button>
                            </div>

                            {/* Merchant Info */}
                            <div className="flex items-center gap-3 px-5 py-4">
                                {/* Logo - Auto-generated if not uploaded */}
                                <div className="w-12 h-12 rounded-lg bg-orange-100 flex items-center justify-center overflow-hidden shrink-0">
                                    {merchant.logoUrl ? (
                                        <Image
                                            src={merchant.logoUrl}
                                            alt={merchant.name}
                                            width={48}
                                            height={48}
                                            className="w-full h-full object-cover"
                                        />
                                    ) : (
                                        // eslint-disable-next-line @next/next/no-img-element
                                        <img
                                            src={generateLogoDataUrl(merchant.name, 96)}
                                            alt={merchant.name}
                                            className="w-full h-full object-cover"
                                        />
                                    )}
                                </div>
                                {/* Name & URL */}
                                <div className="flex-1 min-w-0">
                                    <h4 className="text-sm font-semibold text-gray-900 truncate">
                                        {merchant.name}
                                    </h4>
                                    <p className="text-xs text-gray-500 truncate">
                                        {shareUrl}
                                    </p>
                                </div>
                            </div>

                            {/* Share Channels */}
                            <div className="px-5 py-4 border-t border-gray-200">
                                <div className="grid grid-cols-4 gap-4">
                                    {/* X (Twitter) */}
                                    <button
                                        onClick={handleShareX}
                                        className="flex flex-col items-center gap-2"
                                    >
                                        <div className="w-12 h-12 rounded-full bg-black flex items-center justify-center">
                                            <svg width="20" height="20" viewBox="0 0 24 24" fill="white">
                                                <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                                            </svg>
                                        </div>
                                        <span className="text-xs text-gray-600">X</span>
                                    </button>

                                    {/* Facebook */}
                                    <button
                                        onClick={handleShareFacebook}
                                        className="flex flex-col items-center gap-2"
                                    >
                                        <div className="w-12 h-12 rounded-full bg-[#1877F2] flex items-center justify-center">
                                            <svg width="20" height="20" viewBox="0 0 24 24" fill="white">
                                                <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
                                            </svg>
                                        </div>
                                        <span className="text-xs text-gray-600">Facebook</span>
                                    </button>

                                    {/* WhatsApp */}
                                    <button
                                        onClick={handleShareWhatsApp}
                                        className="flex flex-col items-center gap-2"
                                    >
                                        <div className="w-12 h-12 rounded-full bg-[#25D366] flex items-center justify-center">
                                            <svg width="22" height="22" viewBox="0 0 24 24" fill="white">
                                                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
                                            </svg>
                                        </div>
                                        <span className="text-xs text-gray-600">WhatsApp</span>
                                    </button>

                                    {/* LINE */}
                                    <button
                                        onClick={handleShareLine}
                                        className="flex flex-col items-center gap-2"
                                    >
                                        <div className="w-12 h-12 rounded-full bg-[#00B900] flex items-center justify-center">
                                            <svg width="22" height="22" viewBox="0 0 24 24" fill="white">
                                                <path d="M19.365 9.863c.349 0 .63.285.63.631 0 .345-.281.63-.63.63H17.61v1.125h1.755c.349 0 .63.283.63.63 0 .344-.281.629-.63.629h-2.386c-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.63-.63h2.386c.346 0 .627.285.627.63 0 .349-.281.63-.63.63H17.61v1.125h1.755zm-3.855 3.016c0 .27-.174.51-.432.596-.064.021-.133.031-.199.031-.211 0-.391-.09-.51-.25l-2.443-3.317v2.94c0 .344-.279.629-.631.629-.346 0-.626-.285-.626-.629V8.108c0-.27.173-.51.43-.595.06-.023.136-.033.194-.033.195 0 .375.104.495.254l2.462 3.33V8.108c0-.345.282-.63.63-.63.345 0 .63.285.63.63v4.771zm-5.741 0c0 .344-.282.629-.631.629-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.63-.63.346 0 .628.285.628.63v4.771zm-2.466.629H4.917c-.345 0-.63-.285-.63-.629V8.108c0-.345.285-.63.63-.63.348 0 .63.285.63.63v4.141h1.756c.348 0 .629.283.629.63 0 .344-.282.629-.629.629M24 10.314C24 4.943 18.615.572 12 .572S0 4.943 0 10.314c0 4.811 4.27 8.842 10.035 9.608.391.082.923.258 1.058.59.12.301.079.766.038 1.08l-.164 1.02c-.045.301-.24 1.186 1.049.645 1.291-.539 6.916-4.078 9.436-6.975C23.176 14.393 24 12.458 24 10.314" />
                                            </svg>
                                        </div>
                                        <span className="text-xs text-gray-600">LINE</span>
                                    </button>
                                </div>

                                {/* Second Row */}
                                <div className="grid grid-cols-4 gap-4 mt-4">
                                    {/* Copy Link */}
                                    <button
                                        onClick={handleCopyLink}
                                        className="flex flex-col items-center gap-2"
                                    >
                                        <div className={`w-12 h-12 rounded-full ${copySuccess ? 'bg-green-500' : 'bg-gray-200'} flex items-center justify-center transition-colors`}>
                                            {copySuccess ? (
                                                <svg width="20" height="20" viewBox="0 0 24 24" fill="white">
                                                    <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
                                                </svg>
                                            ) : (
                                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-600">
                                                    <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
                                                    <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
                                                </svg>
                                            )}
                                        </div>
                                        <span className="text-xs text-gray-600">
                                            {copySuccess ? 'Copied!' : 'Copy Link'}
                                        </span>
                                    </button>

                                    {/* Email */}
                                    <button
                                        onClick={handleShareEmail}
                                        className="flex flex-col items-center gap-2"
                                    >
                                        <div className="w-12 h-12 rounded-full bg-gray-200 flex items-center justify-center">
                                            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-600">
                                                <rect x="2" y="4" width="20" height="16" rx="2" />
                                                <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
                                            </svg>
                                        </div>
                                        <span className="text-xs text-gray-600">E-Mail</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </>
            )}

            <style jsx>{`
                @keyframes slide-up {
                    from {
                        transform: translateY(100%);
                    }
                    to {
                        transform: translateY(0);
                    }
                }
                .animate-slide-up {
                    animation: slide-up 0.3s ease-out;
                }
                @keyframes slide-down {
                    from {
                        transform: translateY(0);
                    }
                    to {
                        transform: translateY(100%);
                    }
                }
                .animate-slide-down {
                    animation: slide-down 0.25s ease-in forwards;
                }
                @keyframes scale-in {
                    from {
                        opacity: 0;
                        transform: scale(0.95);
                    }
                    to {
                        opacity: 1;
                        transform: scale(1);
                    }
                }
                .animate-scale-in {
                    animation: scale-in 0.2s ease-out;
                }
            `}</style>
        </>
    );
}
