/**
 * Restaurant Info Card Component - Burjo ESB Style
 * 
 * @description
 * Display merchant information with opening hours and logo
 * Matches Burjo ESB reference:
 * - Border: 0.66px solid #E6E6E6
 * - Border Radius: 16px
 * - Shadow: 0 2px 8px rgba(0,0,0,0.08)
 * - Store name: 16px, weight 700, #212529
 * - Business hours: 14px, #666
 * - Logo: 48x48px, rounded-lg (slightly rounded square)
 * 
 * @specification Burjo ESB Reference
 */

'use client';

import { ChevronRight } from 'lucide-react';
import Image from 'next/image';
import { useTranslation } from '@/lib/i18n/useTranslation';
import { getLogoUrl } from '@/lib/utils/autoGeneratedImages';

interface OpeningHour {
  dayOfWeek: number;
  openTime: string;
  closeTime: string;
  isClosed: boolean;
}

interface RestaurantInfoCardProps {
  name: string;
  openingHours: OpeningHour[];
  onClick?: () => void;
  isClosed?: boolean; // When true, show red CLOSED badge
  logoUrl?: string | null; // Merchant logo URL
}

export default function RestaurantInfoCard({ name, openingHours, onClick, isClosed = false, logoUrl }: RestaurantInfoCardProps) {
  const { t } = useTranslation();

  // Get logo URL - use uploaded logo or generate one
  const displayLogoUrl = getLogoUrl(name, logoUrl);

  // Calculate merchant status
  const getMerchantStatus = (): string => {
    if (!openingHours || openingHours.length === 0) {
      return t('customer.hours.unknown');
    }

    const now = new Date();
    const currentDay = now.getDay();

    const todayHours = openingHours.find(h => h.dayOfWeek === currentDay);

    if (!todayHours || todayHours.isClosed) {
      return t('customer.hours.closedToday');
    }

    const { openTime, closeTime } = todayHours;

    // Format time for display
    const formatTime = (time: string): string => {
      const [hours, minutes] = time.split(':');
      const hour = parseInt(hours);
      const period = hour >= 12 ? 'PM' : 'AM';
      const displayHour = hour > 12 ? hour - 12 : hour === 0 ? 12 : hour;
      return `${displayHour}:${minutes} ${period}`;
    };

    return t('customer.hours.openToday', { hours: `${formatTime(openTime)}-${formatTime(closeTime)}` });
  };

  return (
    <div
      onClick={onClick}
      className="flex items-center justify-between cursor-pointer transition-all duration-200 hover:shadow-md bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-2xl p-4 shadow-sm font-['Inter',sans-serif]"
      role="button"
      tabIndex={0}
      aria-label={`${name} information`}
    >
      <div className="flex items-center gap-3 min-w-0 flex-1">
        {/* Merchant Logo - 48x48px rounded square (1:1 ratio) */}
        <div 
          className="relative shrink-0 overflow-hidden w-12 h-12 rounded-[10px] border border-gray-200 dark:border-gray-700"
        >
          {displayLogoUrl.startsWith('data:') ? (
            // SVG data URL (auto-generated)
            // eslint-disable-next-line @next/next/no-img-element
            <img 
              src={displayLogoUrl} 
              alt={`${name} logo`}
              className="w-full h-full object-cover"
            />
          ) : (
            // Regular image URL (uploaded)
            <Image
              src={displayLogoUrl}
              alt={`${name} logo`}
              fill
              className="object-cover"
              sizes="48px"
            />
          )}
        </div>

        <div className="min-w-0 flex-1">
          {/* Name and CLOSED badge in same row */}
          <div className="flex items-center gap-2">
            <h2
              className="font-bold truncate text-base text-gray-900 dark:text-white font-['Inter',sans-serif]"
            >
              {name}
            </h2>
            {/* CLOSED Badge - Show when store is closed */}
            {isClosed && (
              <span
                className="shrink-0 bg-red-500 text-white px-1.5 py-0.5 rounded text-[10px] font-bold font-['Inter',sans-serif] uppercase tracking-wide"
              >
                {t('common.closed')}
              </span>
            )}
          </div>
          <p
            className="truncate text-sm text-gray-500 dark:text-gray-400 font-['Inter',sans-serif]"
          >
            {getMerchantStatus()}
          </p>
        </div>
      </div>
      <ChevronRight className="text-gray-400 dark:text-gray-500 shrink-0" width="20" height="20" />
    </div>
  );
}

