/**
 * Restaurant Banner Component - Burjo ESB Style
 * 
 * @description
 * Banner image for merchant with auto-generated fallback
 * Matches Burjo ESB reference:
 * - Height: 214px
 * - Border radius: 8px bottom corners
 * - Object-fit: cover
 * 
 * Auto-generates professional banner from merchant name if no banner uploaded
 * 
 * @specification Burjo ESB Reference
 */

'use client';

import { useState, useEffect, useMemo } from 'react';
import { generateBannerDataUrl } from '@/lib/utils/autoGeneratedImages';

interface RestaurantBannerProps {
  imageUrl?: string | null;
  bannerUrl?: string | null;
  merchantName: string;
  isClosed?: boolean; // When true, apply gray overlay
}

export default function RestaurantBanner({ imageUrl, bannerUrl, merchantName, isClosed = false }: RestaurantBannerProps) {
  // Use a cache-busting parameter that updates every 30 seconds
  // This ensures fresh images are loaded when banner is updated
  const [cacheBuster, setCacheBuster] = useState(() => Math.floor(Date.now() / 30000));

  useEffect(() => {
    // Update cache buster when bannerUrl changes
    setCacheBuster(Math.floor(Date.now() / 30000));
  }, [bannerUrl]);

  // Generate auto-banner if no banner or logo uploaded
  const autoGeneratedBanner = useMemo(() => {
    if (!bannerUrl && !imageUrl) {
      return generateBannerDataUrl(merchantName, 1200, 400);
    }
    return null;
  }, [bannerUrl, imageUrl, merchantName]);

  // Use bannerUrl if available, then imageUrl (logo), then auto-generated
  const baseImage = bannerUrl || imageUrl || autoGeneratedBanner || '/images/no-outlet.png';

  // Add cache-busting for external URLs (blob storage) to prevent stale cached images
  // Don't add cache buster to data URLs
  const displayImage = baseImage.startsWith('http')
    ? `${baseImage}${baseImage.includes('?') ? '&' : '?'}v=${cacheBuster}`
    : baseImage;

  return (
    <div
      className="relative w-full bg-gray-100 overflow-hidden"
      style={{
        height: '214px',
        borderRadius: '0 0 8px 8px', // Bottom corners only
      }}
    >
      {/* Banner Image */}
      <div className={`relative w-full h-full ${isClosed ? 'grayscale opacity-60' : ''}`}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={displayImage}
          alt={merchantName}
          className="w-full h-full object-cover"
          onError={(e) => {
            const target = e.target as HTMLImageElement;
            // If image fails to load, try auto-generated banner
            if (!target.src.startsWith('data:')) {
              target.src = generateBannerDataUrl(merchantName, 1200, 400);
            }
          }}
        />
      </div>
      
      {/* Gray overlay when closed */}
      {isClosed && (
        <div 
          className="absolute inset-0 bg-gray-900/30 pointer-events-none"
          style={{ borderRadius: '0 0 8px 8px' }}
        />
      )}
    </div>
  );
}

