"use client";

import React, { useState, useEffect, useCallback } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { isStoreEffectivelyOpen, type OpeningHour } from "@/lib/utils/storeStatus";
import { getLogoUrl } from "@/lib/utils/autoGeneratedImages";

interface MerchantData {
  id: string;
  name: string;
  code: string;
  logoUrl: string | null;
  isActive: boolean;
  isOpen: boolean;
  isManualOverride: boolean;
  openingHours: OpeningHour[];
  timezone?: string;
}

interface MerchantBannerProps {
  isExpanded: boolean;
}

/**
 * Merchant Banner Component
 * Displays merchant info in sidebar with logo, name, and status
 * Clickable to navigate to merchant view page
 */
const MerchantBanner: React.FC<MerchantBannerProps> = ({ isExpanded }) => {
  const router = useRouter();
  const [merchant, setMerchant] = useState<MerchantData | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchMerchantData = useCallback(async () => {
    try {
      const token = localStorage.getItem("accessToken");
      if (!token) return;

      const response = await fetch("/api/merchant/profile", {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (response.ok) {
        const data = await response.json();
        const merchantData = data.data?.merchant || data.data;
        
        // Map openingHours to match OpeningHour type
        const openingHours: OpeningHour[] = (merchantData.openingHours || []).map((h: {
          dayOfWeek: number;
          openTime?: string | null;
          closeTime?: string | null;
          isClosed: boolean;
          is24Hours?: boolean;
        }) => ({
          dayOfWeek: h.dayOfWeek,
          openTime: h.openTime,
          closeTime: h.closeTime,
          isClosed: h.isClosed,
          is24Hours: h.is24Hours,
        }));
        
        // Calculate effective open status using unified utility
        const effectivelyOpen = isStoreEffectivelyOpen({
          isOpen: merchantData.isOpen,
          isManualOverride: merchantData.isManualOverride,
          openingHours,
          timezone: merchantData.timezone,
        });
        
        setMerchant({
          id: merchantData.id,
          name: merchantData.name,
          code: merchantData.code,
          logoUrl: merchantData.logoUrl,
          isActive: merchantData.isActive,
          isOpen: effectivelyOpen,
          isManualOverride: merchantData.isManualOverride ?? false,
          openingHours,
          timezone: merchantData.timezone,
        });
      }
    } catch (error) {
      console.error("Failed to fetch merchant data:", error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchMerchantData();
    
    // Listen for merchant status updates
    const handleStatusUpdate = () => {
      fetchMerchantData();
    };
    
    window.addEventListener('merchantStatusUpdated', handleStatusUpdate);
    window.addEventListener('focus', handleStatusUpdate);
    
    return () => {
      window.removeEventListener('merchantStatusUpdated', handleStatusUpdate);
      window.removeEventListener('focus', handleStatusUpdate);
    };
  }, [fetchMerchantData]);

  const handleClick = () => {
    router.push("/admin/dashboard/merchant/view");
  };

  if (loading) {
    return (
      <div className="mb-2 animate-pulse">
        <div className={`flex items-center gap-3 rounded-xl border border-gray-200 bg-gray-50 p-3 dark:border-gray-800 dark:bg-gray-900/50 ${isExpanded ? '' : 'justify-center'}`}>
          <div className="h-12 w-12 rounded-xl bg-gray-200 dark:bg-gray-700"></div>
          {isExpanded && (
            <div className="flex-1">
              <div className="h-4 w-24 rounded bg-gray-200 dark:bg-gray-700"></div>
              <div className="mt-2 h-3 w-16 rounded bg-gray-200 dark:bg-gray-700"></div>
            </div>
          )}
        </div>
      </div>
    );
  }

  if (!merchant) return null;

  // Determine status color and text
  const getStatusConfig = () => {
    if (!merchant.isActive) {
      return {
        color: "text-gray-600 dark:text-gray-400",
        bgColor: "bg-gray-50 dark:bg-gray-900/50",
        borderColor: "border-gray-200 dark:border-gray-700",
        dotColor: "bg-gray-400",
        ringColor: "ring-gray-400/20",
        text: "Inactive",
      };
    }
    
    if (merchant.isOpen) {
      return {
        color: "text-success-700 dark:text-success-400",
        bgColor: "bg-success-50 dark:bg-success-900/20",
        borderColor: "border-success-200 dark:border-success-800",
        dotColor: "bg-success-500",
        ringColor: "ring-success-500/20",
        text: merchant.isManualOverride ? "Open (Manual)" : "Open Now",
      };
    }
    
    return {
      color: "text-red-700 dark:text-red-400",
      bgColor: "bg-red-50 dark:bg-red-900/20",
      borderColor: "border-red-200 dark:border-red-800",
      dotColor: "bg-red-500",
      ringColor: "ring-red-500/20",
      text: merchant.isManualOverride ? "Closed (Manual)" : "Closed",
    };
  };

  const statusConfig = getStatusConfig();

  // Get logo URL - use uploaded logo or generate one
  const displayLogoUrl = getLogoUrl(merchant.name, merchant.logoUrl);

  return (
    <div className="mb-2">
      <button
        onClick={handleClick}
        className={`group relative w-full transition-all duration-200 ${
          isExpanded 
            ? `rounded-xl border ${statusConfig.borderColor} bg-white dark:bg-gray-900 p-4 hover:shadow-md hover:border-gray-300 dark:hover:border-gray-700`
            : 'flex justify-center'
        }`}
      >
        
        <div className={`relative ${isExpanded ? 'flex items-center gap-4' : ''}`}>
          {/* Logo with status indicator */}
          <div className="relative shrink-0">
            {isExpanded ? (
              <>
                <div className={`relative overflow-hidden rounded-xl h-14 w-14 border-2 ${statusConfig.borderColor} bg-white shadow-sm dark:bg-gray-800`}>
                  {displayLogoUrl.startsWith('data:') ? (
                    // SVG data URL (auto-generated)
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={displayLogoUrl}
                      alt={merchant.name}
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <Image
                      src={displayLogoUrl}
                      alt={merchant.name}
                      fill
                      className="object-cover"
                    />
                  )}
                </div>
                {/* Status dot indicator */}
                <div className={`absolute -bottom-0.5 -right-0.5 h-4 w-4 rounded-full ${statusConfig.dotColor} border-2 border-white dark:border-gray-900 shadow-sm`}></div>
              </>
            ) : (
              /* Minimized: Only logo with prominent dot */
              <div className="relative">
                <div className={`relative overflow-hidden rounded-xl h-12 w-12 border-2 ${statusConfig.borderColor} bg-white shadow-md dark:bg-gray-800 transition-all group-hover:scale-110`}>
                  {displayLogoUrl.startsWith('data:') ? (
                    // SVG data URL (auto-generated)
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={displayLogoUrl}
                      alt={merchant.name}
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <Image
                      src={displayLogoUrl}
                      alt={merchant.name}
                      fill
                      className="object-cover"
                    />
                  )}
                </div>
                {/* Large prominent status dot */}
                <div className={`absolute -bottom-1 -right-1 h-5 w-5 rounded-full ${statusConfig.dotColor} border-[3px] border-white dark:border-gray-900 shadow-lg ring-4 ${statusConfig.ringColor} transition-all group-hover:scale-110`}>
                  {merchant.isActive && merchant.isOpen && (
                    <div className={`h-full w-full rounded-full ${statusConfig.dotColor} animate-pulse`}></div>
                  )}
                </div>
              </div>
            )}
          </div>

          {/* Merchant Info - Only show when expanded */}
          {isExpanded && (
            <>
              <div className="flex-1 text-left">
                <h3 className="line-clamp-1 text-sm font-bold text-gray-900 dark:text-white">
                  {merchant.name}
                </h3>
                <div className={`mt-1 flex items-center gap-1.5 text-xs font-semibold ${statusConfig.color}`}>
                  <div className={`h-1.5 w-1.5 rounded-full ${statusConfig.dotColor} animate-pulse`}></div>
                  <span>{statusConfig.text}</span>
                </div>
              </div>

              {/* Arrow indicator */}
              <svg
                className={`h-5 w-5 shrink-0 ${statusConfig.color} transition-transform group-hover:translate-x-1`}
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 5l7 7-7 7" />
              </svg>
            </>
          )}
        </div>
      </button>
    </div>
  );
};

export default MerchantBanner;
