"use client";

import React, { useMemo } from "react";
import Image from "next/image";
import { generateLogoDataUrl, generateBannerDataUrl } from "@/lib/utils/autoGeneratedImages";

interface AutoLogoProps {
  merchantName: string;
  logoUrl?: string | null;
  size?: number;
  className?: string;
  priority?: boolean;
}

/**
 * Auto Logo Component
 * Shows uploaded logo if available, otherwise generates a professional logo from merchant name
 */
export function AutoLogo({
  merchantName,
  logoUrl,
  size = 64,
  className = "",
  priority = false,
}: AutoLogoProps) {
  const imageUrl = useMemo(() => {
    if (logoUrl) return logoUrl;
    return generateLogoDataUrl(merchantName, size * 2); // 2x for retina
  }, [merchantName, logoUrl, size]);

  const isDataUrl = imageUrl.startsWith("data:");

  return (
    <div
      className={`relative overflow-hidden rounded-full ${className}`}
      style={{ width: size, height: size }}
    >
      {isDataUrl ? (
        // For data URLs, use regular img tag (Next.js Image doesn't support data URLs well)
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={imageUrl}
          alt={`${merchantName} logo`}
          className="h-full w-full object-cover"
        />
      ) : (
        <Image
          src={imageUrl}
          alt={`${merchantName} logo`}
          fill
          className="object-cover"
          priority={priority}
          unoptimized
        />
      )}
    </div>
  );
}

interface AutoBannerProps {
  merchantName: string;
  bannerUrl?: string | null;
  width?: number;
  height?: number;
  className?: string;
  priority?: boolean;
}

/**
 * Auto Banner Component
 * Shows uploaded banner if available, otherwise generates a professional banner from merchant name
 */
export function AutoBanner({
  merchantName,
  bannerUrl,
  width = 1200,
  height = 400,
  className = "",
  priority = false,
}: AutoBannerProps) {
  const imageUrl = useMemo(() => {
    if (bannerUrl) return bannerUrl;
    return generateBannerDataUrl(merchantName, width, height);
  }, [merchantName, bannerUrl, width, height]);

  const isDataUrl = imageUrl.startsWith("data:");

  return (
    <div
      className={`relative w-full overflow-hidden ${className}`}
      style={{ aspectRatio: `${width}/${height}` }}
    >
      {isDataUrl ? (
        // For data URLs, use regular img tag
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={imageUrl}
          alt={`${merchantName} banner`}
          className="h-full w-full object-cover"
        />
      ) : (
        <Image
          src={imageUrl}
          alt={`${merchantName} banner`}
          fill
          className="object-cover"
          priority={priority}
          unoptimized
        />
      )}
    </div>
  );
}

/**
 * Logo with fallback badge
 * Shows a small badge when using auto-generated logo
 */
interface AutoLogoWithBadgeProps extends AutoLogoProps {
  showBadge?: boolean;
}

export function AutoLogoWithBadge({
  merchantName,
  logoUrl,
  size = 64,
  className = "",
  priority = false,
  showBadge = true,
}: AutoLogoWithBadgeProps) {
  const isAutoGenerated = !logoUrl;

  return (
    <div className="relative inline-block">
      <AutoLogo
        merchantName={merchantName}
        logoUrl={logoUrl}
        size={size}
        className={className}
        priority={priority}
      />
      {showBadge && isAutoGenerated && (
        <div 
          className="absolute -bottom-1 -right-1 rounded-full bg-gray-100 px-1.5 py-0.5 text-[8px] font-medium text-gray-500 shadow-sm dark:bg-gray-700 dark:text-gray-400"
          title="Auto-generated logo"
        >
          Auto
        </div>
      )}
    </div>
  );
}

/**
 * Banner with upload prompt overlay
 * Shows an overlay suggesting to upload a custom banner when using auto-generated
 */
interface AutoBannerWithPromptProps extends AutoBannerProps {
  showPrompt?: boolean;
  onUploadClick?: () => void;
}

export function AutoBannerWithPrompt({
  merchantName,
  bannerUrl,
  width = 1200,
  height = 400,
  className = "",
  priority = false,
  showPrompt = true,
  onUploadClick,
}: AutoBannerWithPromptProps) {
  const isAutoGenerated = !bannerUrl;

  return (
    <div className="relative">
      <AutoBanner
        merchantName={merchantName}
        bannerUrl={bannerUrl}
        width={width}
        height={height}
        className={className}
        priority={priority}
      />
      {showPrompt && isAutoGenerated && onUploadClick && (
        <div className="absolute inset-0 flex items-center justify-center bg-black/30 opacity-0 transition-opacity hover:opacity-100">
          <button
            onClick={onUploadClick}
            className="rounded-lg bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-lg hover:bg-gray-50"
          >
            Upload Custom Banner
          </button>
        </div>
      )}
    </div>
  );
}
