/**
 * Addon Tutorial Steps
 * Create and manage addon categories and items
 */

import type { TutorialStep } from '../types';

// ============================================
// CREATE ADDON CATEGORY TUTORIAL
// ============================================

export const createAddonCategorySteps: TutorialStep[] = [
  {
    id: 'go-to-addon-categories',
    title: 'Go to Addon Categories',
    description: 'Addon categories group related customization options (e.g., "Size", "Spice Level", "Extra Toppings"). Let\'s create one!',
    targetSelector: '[data-nav-item="/admin/dashboard/addon-categories"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Addon Categories',
    navigateTo: '/admin/dashboard/addon-categories',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
  },
  {
    id: 'addon-categories-page',
    title: 'Addon Categories Page',
    description: 'This page helps you organize addons before linking them to menu items.',
    targetSelector: '[data-tutorial="addon-categories-page"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'addon-category-filters',
    title: 'Filters',
    description: 'Filter and sort to find the right addon category quickly.',
    targetSelector: '[data-tutorial="addon-category-filters"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'addon-category-search',
    title: 'Search',
    description: 'Type a name to find a category fast.',
    targetSelector: '[data-tutorial="addon-category-search"]',
    position: 'bottom',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
    pointerIcon: 'search',
  },
  {
    id: 'addon-category-overview',
    title: 'Addon Categories List',
    description: 'Here you can see all your addon categories. Each category contains multiple addon items that customers can choose from.',
    targetSelector: '[data-tutorial="addon-category-list"], [data-tutorial="addon-category-empty-state"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'click-add-addon-category',
    title: 'Click "Add Addon Category"',
    description: 'Click this button to create a new addon category. Examples: "Choose Size", "Spice Level", "Extra Toppings".',
    targetSelector: '[data-tutorial="add-addon-category-btn"]',
    position: 'bottom-left',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
    pointerIcon: 'plus',
    actionText: 'Open Form',
  },
  {
    id: 'addon-category-modal',
    title: 'Addon Category Form',
    description: 'Fill in the addon category details. This defines how customers can customize their orders.',
    targetSelector: '[data-tutorial="addon-category-form-modal"]',
    position: 'right',
    spotlightPadding: 12,
  },
  {
    id: 'addon-category-form',
    title: 'Category Details',
    description: 'Complete the form to define how customers will pick options.',
    targetSelector: '[data-tutorial="addon-category-form"]',
    position: 'right',
    spotlightPadding: 12,
  },
  {
    id: 'addon-category-name',
    title: 'Enter Category Name',
    description: 'Give a clear name that tells customers what to choose. Examples: "Choose Your Size", "Select Toppings", "Spice Level".',
    targetSelector: '[data-tutorial="addon-category-name-field"]',
    position: 'right',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
    pointerIcon: 'edit',
  },
  {
    id: 'addon-category-type',
    title: 'Selection Type',
    description: 'Choose how customers select: "Single" (radio buttons - one choice only) or "Multiple" (checkboxes - can pick several).',
    targetSelector: '[data-tutorial="addon-category-selection-rules"]',
    position: 'right',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
  },
  {
    id: 'addon-category-min-max',
    title: 'Set Min/Max Selections',
    description: 'Set rules for selections:\n• Min 1, Max 1 = Required, exactly one\n• Min 0, Max 3 = Optional, up to 3\n• Min 2, Max 2 = Must choose exactly 2\n\nIf minimum is 1+, the addon becomes required.',
    targetSelector: '[data-tutorial="addon-category-selection-rules"]',
    position: 'right',
    spotlightPadding: 8,
  },
  {
    id: 'addon-category-save',
    title: 'Save Addon Category',
    description: 'Click "Save" to create the addon category. Next, you\'ll add the actual items (options) to this category!',
    targetSelector: '[data-tutorial="addon-category-save-btn"]',
    position: 'top',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
    pointerLabel: 'Save!',
    pointerIcon: 'check',
  },
  {
    id: 'next-create-items',
    title: 'Next: Add Addon Items',
    description: 'Great! Now let\'s add the actual options to your addon category. Click to go to Addon Items page.',
    targetSelector: '[data-nav-item="/admin/dashboard/addon-items"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Addon Items',
    navigateTo: '/admin/dashboard/addon-items',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Next step!',
    pointerIcon: 'arrow-right',
  },
];

// ============================================
// CREATE ADDON ITEM TUTORIAL
// ============================================

export const createAddonItemSteps: TutorialStep[] = [
  {
    id: 'go-to-addon-items',
    title: 'Go to Addon Items',
    description: 'Addon items are the actual options customers can choose (e.g., "Small", "Medium", "Large").',
    targetSelector: '[data-nav-item="/admin/dashboard/addon-items"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Addon Items',
    navigateTo: '/admin/dashboard/addon-items',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
  },
  {
    id: 'addon-items-page',
    title: 'Addon Items Page',
    description: 'Create and manage addon options for each category.',
    targetSelector: '[data-tutorial="addon-items-page"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'addon-items-actions',
    title: 'Quick Actions',
    description: 'Use these buttons to add new items or upload in bulk.',
    targetSelector: '[data-tutorial="addon-items-actions"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'addon-items-overview',
    title: 'Addon Items List',
    description: 'Here you can see all addon items grouped by their category. Each item has a name and an extra price.',
    targetSelector: '[data-tutorial="addon-items-list"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'filter-by-category',
    title: 'Filter by Category',
    description: 'Use this filter to view items in a specific addon category. This helps when you have many addons.',
    targetSelector: '[data-tutorial="addon-item-filter"]',
    position: 'bottom',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
    pointerIcon: 'search',
  },
  {
    id: 'click-add-addon-item',
    title: 'Click "Add Addon Item"',
    description: 'Click this button to create a new addon item. You\'ll assign it to a category you created earlier.',
    targetSelector: '[data-tutorial="add-addon-item-btn"]',
    position: 'bottom-left',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
    pointerIcon: 'plus',
  },
  {
    id: 'addon-item-modal',
    title: 'Addon Item Form',
    description: 'Fill in the addon item details. This is what customers will see as an option.',
    targetSelector: '[data-tutorial="addon-item-modal"]',
    position: 'right',
    spotlightPadding: 12,
  },
  {
    id: 'addon-item-category',
    title: 'Select Addon Category',
    description: 'First, choose which addon category this item belongs to. Example: If adding "Large" size, select "Choose Size" category.',
    targetSelector: '[data-tutorial="addon-item-category"]',
    position: 'right',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
  },
  {
    id: 'addon-item-name',
    title: 'Enter Item Name',
    description: 'Give a clear name for this option. Examples: "Small", "Medium", "Large", "Extra Cheese", "No Onions", "Spicy 🌶️".',
    targetSelector: '[data-tutorial="addon-item-name"]',
    position: 'right',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
    pointerIcon: 'edit',
  },
  {
    id: 'addon-item-price',
    title: 'Set Extra Price',
    description: 'Enter the additional charge for this option. Set to 0 for free options. Example: "Large +$2.00" or "Extra Cheese +$1.50".',
    targetSelector: '[data-tutorial="addon-item-price"]',
    position: 'right',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
  },
  {
    id: 'addon-item-stock',
    title: 'Stock Settings (Optional)',
    description: 'Enable stock tracking if this addon has limited availability. When stock is 0, the option becomes unavailable.',
    targetSelector: '[data-tutorial="addon-item-stock"]',
    position: 'right',
    spotlightPadding: 8,
  },
  {
    id: 'addon-item-save',
    title: 'Save Addon Item',
    description: 'Click "Save" to create the addon item. Repeat this process to add all options to your addon category!',
    targetSelector: '[data-tutorial="addon-item-save-btn"]',
    position: 'top',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
    pointerLabel: 'Save!',
    pointerIcon: 'check',
  },
  {
    id: 'addon-complete',
    title: 'Addon Setup Complete! 🎉',
    description: 'Great job! Now go to Menu Items and link this addon category to your menus. Customers will be able to customize their orders!',
    targetSelector: null,
    position: 'center',
    showSkip: false,
  },
];

// ============================================
// EDIT ADDON TUTORIAL
// ============================================

export const editAddonSteps: TutorialStep[] = [
  {
    id: 'go-to-addon-items',
    title: 'Go to Addon Items',
    description: 'Navigate to Addon Items to edit existing options.',
    targetSelector: '[data-nav-item="/admin/dashboard/addon-items"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Addon Items',
    navigateTo: '/admin/dashboard/addon-items',
  },
  {
    id: 'find-addon',
    title: 'Find the Addon Item',
    description: 'Use the filter to find the addon category, then locate the specific item you want to edit.',
    targetSelector: '[data-tutorial="addon-item-filter"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'click-addon-menu',
    title: 'Click Edit Button',
    description: 'Click the edit button to open the addon item form.',
    targetSelector: '[data-tutorial="addon-item-edit-btn"]',
    position: 'left',
    spotlightPadding: 8,
  },
  {
    id: 'update-addon',
    title: 'Update Addon Details',
    description: 'Make your changes. You can update the name, price, or move it to a different category.',
    targetSelector: '[data-tutorial="addon-item-modal"]',
    position: 'right',
    spotlightPadding: 12,
  },
  {
    id: 'save-changes',
    title: 'Save Changes',
    description: 'Click "Save" to update the addon item. Changes apply immediately to all menus using this addon!',
    targetSelector: '[data-tutorial="addon-item-save-btn"]',
    position: 'top',
    spotlightPadding: 8,
  },
];

// ============================================
// BULK UPLOAD ADDON TUTORIAL
// ============================================

export const bulkUploadAddonSteps: TutorialStep[] = [
  {
    id: 'go-to-addon-items',
    title: 'Go to Addon Items',
    description: 'Navigate to the Addon Items page.',
    targetSelector: '[data-nav-item="/admin/dashboard/addon-items"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Addon Items',
    navigateTo: '/admin/dashboard/addon-items',
  },
  {
    id: 'click-bulk-upload',
    title: 'Click "Bulk Upload"',
    description: 'Click this button to upload multiple addon items at once using a spreadsheet.',
    targetSelector: '[data-tutorial="addon-bulk-upload-btn"]',
    position: 'bottom-left',
    spotlightPadding: 8,
    actionText: 'Open Bulk Upload',
    navigateTo: '/admin/dashboard/addon-items/bulk-upload',
  },
  {
    id: 'download-template',
    title: 'Download Template',
    description: 'Download the Excel template. It includes columns for category, item name, price, and stock.',
    targetSelector: '[data-tutorial="download-template"]',
    position: 'right',
    spotlightPadding: 8,
  },
  {
    id: 'fill-template',
    title: 'Fill the Template',
    description: 'Open in Excel or Google Sheets. Add your addon items. Make sure to use the exact category names from your addon categories!',
    targetSelector: '[data-tutorial="template-guide"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'upload-file',
    title: 'Upload Your File',
    description: 'Drag and drop your filled template here, or click to browse.',
    targetSelector: '[data-tutorial="upload-zone"]',
    position: 'bottom',
    spotlightPadding: 12,
  },
  {
    id: 'preview-and-upload',
    title: 'Preview & Upload',
    description: 'Review the parsed data, fix any errors, then click "Upload All" to create all addon items at once!',
    targetSelector: '[data-tutorial="confirm-upload"]',
    position: 'top',
    spotlightPadding: 8,
  },
];
