/**
 * Onboarding Tutorial Steps
 * First-time merchant/staff login experience
 */

import type { TutorialStep } from '../types';

export const onboardingSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to GENFITY! 🎉',
    description: 'We\'re excited to have you on board! This quick tutorial will guide you through setting up your restaurant for online ordering. It only takes a few minutes.',
    targetSelector: null,
    position: 'center',
    showSkip: true,
    image: '/images/logo/logo.png',
  },
  {
    id: 'getting-started-checklist',
    title: 'Getting Started Checklist',
    description: 'Track your setup progress here. Tap any item to open the right page.',
    targetSelector: '[data-tutorial="getting-started-checklist"]',
    position: 'bottom',
    spotlightPadding: 8,
    navigateTo: '/admin/dashboard',
  },
  {
    id: 'sidebar-intro',
    title: 'Your Dashboard Sidebar',
    description: 'This is your main navigation. Here you\'ll find all the tools to manage your restaurant: orders, menu items, categories, settings, and more.',
    targetSelector: '[data-sidebar]',
    position: 'right',
    spotlightPadding: 0,
    showSkip: true,
    showPointer: true,
    pointerDirection: 'left',
    pointerIcon: 'eye',
  },
  {
    id: 'sidebar-orders',
    title: 'Order Management',
    description: 'View and manage incoming orders in real-time. You can also access the Kitchen Display and Order History from here.',
    targetSelector: '[data-nav-group="orderManagement"]',
    position: 'right',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
  },
  {
    id: 'sidebar-menu',
    title: 'Menu Management',
    description: 'This is where you\'ll create and manage your menu items, categories, addons, and stock. Let\'s set up your menu!',
    targetSelector: '[data-nav-group="menuManagement"]',
    position: 'right',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
    pointerIcon: 'hand-right',
  },
  {
    id: 'merchant-settings-intro',
    title: 'Your Merchant Settings',
    description: 'Great news! Your basic info is already set up from registration. You can update your logo, opening hours, and other settings here anytime.',
    targetSelector: '[data-nav-item="/admin/dashboard/merchant/edit"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'View Settings',
    navigateTo: '/admin/dashboard/merchant/edit',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
    pointerIcon: 'cog',
  },
  {
    id: 'categories-intro',
    title: 'Create Menu Categories',
    description: 'Categories help organize your menu (e.g., "Main Course", "Drinks", "Desserts"). Let\'s create your first category!',
    targetSelector: '[data-nav-item="/admin/dashboard/categories"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Categories',
    navigateTo: '/admin/dashboard/categories',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
    pointerIcon: 'plus',
  },
  {
    id: 'menu-intro',
    title: 'Add Menu Items',
    description: 'Now let\'s add your delicious menu items! You can add photos, descriptions, prices, and assign them to categories.',
    targetSelector: '[data-nav-item="/admin/dashboard/menu"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Menu Items',
    navigateTo: '/admin/dashboard/menu',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Add menu!',
    pointerIcon: 'plus',
  },
  {
    id: 'addons-intro',
    title: 'Addon Categories & Items (Optional)',
    description: 'Add customization options like extra toppings, sizes, or spice levels. This is optional but helps increase sales!',
    targetSelector: '[data-nav-item="/admin/dashboard/addon-categories"]',
    position: 'right',
    spotlightPadding: 4,
    showPointer: true,
    pointerDirection: 'left',
  },
  {
    id: 'qr-tables-intro',
    title: 'Table QR Codes',
    description: 'Generate QR codes for each table so customers can scan and order directly. Perfect for dine-in service!',
    targetSelector: '[data-nav-item="/admin/dashboard/qr-tables"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Set Up QR Codes',
    navigateTo: '/admin/dashboard/qr-tables',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
  },
  {
    id: 'onboarding-complete',
    title: 'You\'re All Set! 🚀',
    description: 'Congratulations! You now know the basics. Need help later? Click the "Help" button in the top navigation bar to access tutorials anytime.',
    targetSelector: null,
    position: 'center',
    showSkip: false,
  },
];
