/**
 * Other Feature Tutorials
 * Staff management, special prices, menu books, and more
 */

import type { TutorialStep } from '../types';

// ============================================
// STAFF MANAGEMENT TUTORIAL
// ============================================

export const staffManagementSteps: TutorialStep[] = [
  {
    id: 'go-to-staff',
    title: 'Go to Staff Management',
    description: 'Manage your team: add staff members, assign roles, and control access permissions.',
    targetSelector: '[data-nav-item="/admin/dashboard/staff"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Staff',
    navigateTo: '/admin/dashboard/staff',
  },
  {
    id: 'staff-overview',
    title: 'Staff Page',
    description: 'This is your staff management page. View all staff members and their roles: Owner, Manager, Cashier, Kitchen Staff, etc.',
    targetSelector: '[data-tutorial="staff-page"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'staff-actions',
    title: 'Staff Actions Panel',
    description: 'Search, filter, and manage staff actions here.',
    targetSelector: '[data-tutorial="staff-actions"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'staff-search',
    title: 'Search Staff',
    description: 'Use the search bar to quickly find staff members by name or email.',
    targetSelector: '[data-tutorial="staff-search"]',
    position: 'bottom',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'staff-buttons',
    title: 'Staff Actions',
    description: 'Use these buttons to add new staff members or invite existing users.',
    targetSelector: '[data-tutorial="staff-buttons"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'add-staff',
    title: 'Add Staff Member',
    description: 'Click this button to add a new team member directly.',
    targetSelector: '[data-tutorial="add-staff-btn"]',
    position: 'bottom-left',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'add-staff-modal',
    title: 'Add Staff Form',
    description: 'Fill in the new staff member details.',
    targetSelector: '[data-tutorial="add-staff-modal"]',
    position: 'right',
    spotlightPadding: 12,
  },
  {
    id: 'staff-name',
    title: 'Staff Name',
    description: 'Enter the staff member\'s full name.',
    targetSelector: '[data-tutorial="staff-name-input"]',
    position: 'right',
    spotlightPadding: 8,
  },
  {
    id: 'staff-email',
    title: 'Staff Email',
    description: 'Add a valid email for login and notifications.',
    targetSelector: '[data-tutorial="staff-email-input"]',
    position: 'right',
    spotlightPadding: 8,
  },
  {
    id: 'staff-phone',
    title: 'Staff Phone',
    description: 'Enter a phone number if needed.',
    targetSelector: '[data-tutorial="staff-phone-input"]',
    position: 'right',
    spotlightPadding: 8,
  },
  {
    id: 'staff-password',
    title: 'Staff Password',
    description: 'Set a temporary password for the staff member.',
    targetSelector: '[data-tutorial="staff-password-input"]',
    position: 'right',
    spotlightPadding: 8,
  },
  {
    id: 'staff-submit',
    title: 'Create Staff Account',
    description: 'Submit the form to create the staff account.',
    targetSelector: '[data-tutorial="staff-submit-btn"]',
    position: 'top',
    spotlightPadding: 8,
  },
  {
    id: 'invite-staff',
    title: 'Invite Staff',
    description: 'Send an invitation email to a new team member. They\'ll receive a link to set up their account.',
    targetSelector: '[data-tutorial="invite-staff-btn"]',
    position: 'bottom-left',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'staff-complete',
    title: 'Staff Management Complete! 👥',
    description: 'Your team can now access the dashboard with their assigned permissions. Each staff member uses their own login.',
    targetSelector: null,
    position: 'center',
    showSkip: false,
  },
];

// ============================================
// SPECIAL PRICES TUTORIAL
// ============================================

export const specialPricesSteps: TutorialStep[] = [
  {
    id: 'go-to-special-prices',
    title: 'Go to Special Prices',
    description: 'Create time-based discounts: happy hour, lunch specials, weekend deals, and promotional pricing.',
    targetSelector: '[data-nav-item="/admin/dashboard/special-prices"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Special Prices',
    navigateTo: '/admin/dashboard/special-prices',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
  },
  {
    id: 'special-prices-overview',
    title: 'Special Prices Page',
    description: 'This is your special prices page. View all your scheduled price changes. Active specials are highlighted.',
    targetSelector: '[data-tutorial="special-prices-page"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'special-prices-header',
    title: 'Page Header',
    description: 'The header shows the page title and provides quick access to create new special prices.',
    targetSelector: '[data-tutorial="special-prices-header"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'add-special-price',
    title: 'Create Special Price',
    description: 'Click this button to create a new promotion. You\'ll be able to select menu items and set discount amounts.',
    targetSelector: '[data-tutorial="special-prices-create"]',
    position: 'bottom',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'special-prices-search',
    title: 'Search Special Prices',
    description: 'Use the search bar to quickly find specific special prices by name.',
    targetSelector: '[data-tutorial="special-prices-search"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'special-prices-empty',
    title: 'No Specials Yet',
    description: 'If this list is empty, create your first special price.',
    targetSelector: '[data-tutorial="special-prices-empty"]',
    position: 'top',
    spotlightPadding: 8,
  },
  {
    id: 'special-prices-list',
    title: 'Special Prices List',
    description: 'View all your special prices here. Active specials are highlighted. Click to edit or delete.',
    targetSelector: '[data-tutorial="special-prices-list"]',
    position: 'top',
    spotlightPadding: 8,
  },
  {
    id: 'special-complete',
    title: 'Special Prices Complete! 🎉',
    description: 'Your special pricing is set! Customers will see discounted prices during the scheduled times.',
    targetSelector: null,
    position: 'center',
    showSkip: false,
  },
];

// ============================================
// SPECIAL PRICES CREATE/EDIT TUTORIAL
// ============================================

export const specialPriceFormSteps: TutorialStep[] = [
  {
    id: 'special-price-create-page',
    title: 'Create Special Price Page',
    description: 'Set up a new special price promotion here.',
    targetSelector: '[data-tutorial="special-price-create-page"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'special-price-basic-info',
    title: 'Basic Information',
    description: 'Enter the name and optional details for your special price.',
    targetSelector: '[data-tutorial="special-price-basic-info"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'special-price-form-overview',
    title: 'Special Price Form',
    description: 'Fill in the details to create or edit a special price promotion.',
    targetSelector: '[data-tutorial="special-price-form"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'special-price-name',
    title: 'Enter Name',
    description: 'Give your special price a descriptive name, e.g., "Happy Hour Discount" or "Weekend Special".',
    targetSelector: '[data-tutorial="special-price-name"]',
    position: 'bottom',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'special-price-dates',
    title: 'Set Date Range',
    description: 'Define when this special price is valid. Set a start and end date for your promotion.',
    targetSelector: '[data-tutorial="special-price-dates"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'special-price-days',
    title: 'Select Applicable Days',
    description: 'Choose which days of the week this special applies. Perfect for "Taco Tuesday" or "Friday Deals".',
    targetSelector: '[data-tutorial="special-price-days"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'special-price-promo-editor',
    title: 'Set Promo Prices',
    description: 'Adjust the promotional prices for each menu item. You\'ll see the original price and can set your discounted price.',
    targetSelector: '[data-tutorial="special-price-promo-editor"]',
    position: 'top',
    spotlightPadding: 8,
  },
  {
    id: 'special-price-status',
    title: 'Toggle Status',
    description: 'Use this toggle to activate or deactivate the special price. Inactive specials won\'t apply to orders.',
    targetSelector: '[data-tutorial="special-price-status"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
];

// ============================================
// MENU BOOKS TUTORIAL
// ============================================

export const menuBooksSteps: TutorialStep[] = [
  {
    id: 'go-to-menu-books',
    title: 'Go to Menu Books',
    description: 'Create different menus for different occasions: Dine-in Menu, Takeaway Menu, Catering Menu, etc.',
    targetSelector: '[data-nav-item="/admin/dashboard/menu-books"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Menu Books',
    navigateTo: '/admin/dashboard/menu-books',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
  },
  {
    id: 'menu-books-overview',
    title: 'Menu Books Page',
    description: 'This is your menu books page. Each "menu book" is a separate menu with its own items and settings.',
    targetSelector: '[data-tutorial="menu-books-page"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'menu-books-header',
    title: 'Page Header',
    description: 'The header provides quick access to create new menu books.',
    targetSelector: '[data-tutorial="menu-books-header"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'create-menu-book',
    title: 'Create Menu Book',
    description: 'Click to create a new menu book. Examples: "Dine-in", "Takeaway", "Delivery Only", "Catering".',
    targetSelector: '[data-tutorial="menu-books-create"]',
    position: 'bottom',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'menu-books-search',
    title: 'Search Menu Books',
    description: 'Use the search bar to quickly find specific menu books by name.',
    targetSelector: '[data-tutorial="menu-books-search"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'menu-books-empty',
    title: 'No Menu Books Yet',
    description: 'Create your first menu book to start organizing menus.',
    targetSelector: '[data-tutorial="menu-books-empty"]',
    position: 'top',
    spotlightPadding: 8,
  },
  {
    id: 'menu-books-list',
    title: 'Menu Books List',
    description: 'View all your menu books here. Click any menu book to edit or manage its items.',
    targetSelector: '[data-tutorial="menu-books-list"]',
    position: 'top',
    spotlightPadding: 8,
  },
  {
    id: 'menu-books-complete',
    title: 'Menu Books Complete! 📚',
    description: 'Create multiple menu books for different occasions. Each can have different items and pricing!',
    targetSelector: null,
    position: 'center',
    showSkip: false,
  },
];

// ============================================
// MENU BOOKS CREATE/EDIT TUTORIAL
// ============================================

export const menuBookFormSteps: TutorialStep[] = [
  {
    id: 'menu-book-create-page',
    title: 'Create Menu Book Page',
    description: 'Set up a new menu book here.',
    targetSelector: '[data-tutorial="menu-book-create-page"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'menu-book-form-overview',
    title: 'Menu Book Form',
    description: 'Fill in the details to create or edit a menu book.',
    targetSelector: '[data-tutorial="menu-book-form"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'menu-book-name',
    title: 'Enter Name',
    description: 'Give your menu book a descriptive name, e.g., "Lunch Special Menus" or "Weekend Brunch".',
    targetSelector: '[data-tutorial="menu-book-name"]',
    position: 'bottom',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'menu-book-basic-info',
    title: 'Basic Information',
    description: 'Enter the name and optional description for your menu book.',
    targetSelector: '[data-tutorial="menu-book-basic-info"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'menu-book-selection',
    title: 'Select Menu Items',
    description: 'Choose which menu items to include in this menu book. Search and select from your existing menus.',
    targetSelector: '[data-tutorial="menu-book-selection"]',
    position: 'top',
    spotlightPadding: 8,
  },
  {
    id: 'menu-book-search',
    title: 'Search Menus',
    description: 'Use this search to quickly find specific menu items to add to your menu book.',
    targetSelector: '[data-tutorial="menu-book-search"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'menu-book-status',
    title: 'Toggle Status',
    description: 'Use this toggle to activate or deactivate the menu book. Inactive menu books won\'t be visible to customers.',
    targetSelector: '[data-tutorial="menu-book-status"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
];

// ============================================
// CUSTOMERS MANAGEMENT TUTORIAL (Super Admin)
// ============================================

export const customersManagementSteps: TutorialStep[] = [
  {
    id: 'go-to-customers',
    title: 'Go to Customers',
    description: 'View and manage all registered customer accounts across the platform.',
    targetSelector: '[data-nav-item="/admin/dashboard/customers"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Customers',
    navigateTo: '/admin/dashboard/customers',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
  },
  {
    id: 'customers-overview',
    title: 'Customers Page',
    description: 'This is your customer management page. View all registered customers, their order history, and spending patterns.',
    targetSelector: '[data-tutorial="customers-page"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'customers-container',
    title: 'Customers Workspace',
    description: 'All customer tools live inside this workspace.',
    targetSelector: '[data-tutorial="customers-container"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'customers-search',
    title: 'Search Customers',
    description: 'Use the search bar to find customers by name, email, or phone number.',
    targetSelector: '[data-tutorial="customers-search"]',
    position: 'bottom',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'customers-actions',
    title: 'Customer Actions',
    description: 'Filter by status, show advanced filters, export to CSV, or refresh the list.',
    targetSelector: '[data-tutorial="customers-actions"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'customers-filters',
    title: 'Advanced Filters',
    description: 'Filter customers by registration date, total spent, or order count. Great for finding your top customers!',
    targetSelector: '[data-tutorial="customers-filters"]',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'customers-table',
    title: 'Customer List',
    description: 'View customer details, order count, total spent, and status. Click "View" to see detailed order history.',
    targetSelector: '[data-tutorial="customers-table"]',
    position: 'top',
    spotlightPadding: 8,
  },
  {
    id: 'customers-complete',
    title: 'Customer Management Complete! 👥',
    description: 'You can now manage customer accounts, view their order history, and export data for marketing purposes.',
    targetSelector: null,
    position: 'center',
    showSkip: false,
  },
];

// ============================================
// LINK MENU TO ADDON TUTORIAL
// ============================================

export const linkMenuToAddonSteps: TutorialStep[] = [
  {
    id: 'go-to-menu',
    title: 'Go to Menu Items',
    description: 'Let\'s link addon categories to your menu items so customers can customize their orders.',
    targetSelector: '[data-nav-item="/admin/dashboard/menu"]',
    position: 'right',
    spotlightPadding: 4,
    actionText: 'Go to Menu',
    navigateTo: '/admin/dashboard/menu',
    showPointer: true,
    pointerDirection: 'left',
    pointerLabel: 'Click here!',
  },
  {
    id: 'find-menu-item',
    title: 'Find Menu Item',
    description: 'Locate the menu item you want to add customization options to.',
    targetSelector: '[data-tutorial="menu-card"]',
    position: 'right',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'left',
  },
  {
    id: 'click-edit-menu',
    title: 'Edit Menu Item',
    description: 'Click the actions button (three dots), then choose "Edit" to modify this menu item.',
    targetSelector: '[data-tutorial="menu-actions-btn"]',
    position: 'left',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'right',
  },
  {
    id: 'addon-section',
    title: 'Addon Categories Section',
    description: 'In the edit form, scroll down to the "Addon Categories" section.',
    targetSelector: '[data-tutorial="menu-addons"]',
    position: 'top',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
  },
  {
    id: 'select-addons',
    title: 'Select Addon Categories',
    description: 'Check the addon categories you want to offer for this item. Customers will see these options when ordering.',
    targetSelector: '[data-tutorial="menu-addons"]',
    position: 'right',
    spotlightPadding: 8,
  },
  {
    id: 'save-menu-with-addons',
    title: 'Save Changes',
    description: 'Click "Save" to apply. This menu item now has customization options!',
    targetSelector: '[data-tutorial="menu-save-btn"]',
    position: 'top',
    spotlightPadding: 8,
    showPointer: true,
    pointerDirection: 'up',
    pointerLabel: 'Save!',
  },
  {
    id: 'link-complete',
    title: 'Addon Linked! 🔗',
    description: 'Customers can now customize this item with your addon options. Test it by viewing your customer menu!',
    targetSelector: null,
    position: 'center',
    showSkip: false,
  },
];
